### ISSUE TITLE
Week1

### ISSUE THREAD

**Issue by SaschaVanEssen** [markpijnenburg/project#1]
Je hebt nog geen processbook. Zorg dat je elke dag je voortgang naar GitHub pusht en je PROCESS.md update. In je DESIGN.md werkt de link naar Flow.png niet. Alle code in 1 main.js wordt al snel onoverzichtelijk. Update je DESIGN.md als je verschillende files maakt zodat we weten welke functies waar te vinden zijn

**Comment by markpijnenburg** [comment]
PROCESS.md toegevoegd, flow.png gefixt. DESIGN.md updated met beschrijving hoe de code in meerdere files gesplitst wordt. Mocht ik hier later nog veranderingen aan toebrengen dan update ik mijn DESIGN.md.
